<h1 align='center'> CS353 Machine Learning Lab</h1>
<h1 align='center'>05/03/21</h1>
<h2 align='center'>Shumbul Arifa (181CO152)</h2>

In [101]:
%matplotlib inline
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from scipy.stats import norm
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report, plot_confusion_matrix
import matplotlib.pyplot as plt

In [102]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/cvcnuwicngektqaaapuqxw45lpngsj')

In [103]:
df.head()

1254   0   40    1  1.1   0.1   0.2  Unnamed: 7
0   -9.0   2  140    0  289  -9.0  -9.0        -9.0
1    0.0  -9   -9    0   12  16.0  84.0         0.0
2    0.0   0    0    0  150  18.0  -9.0         7.0
3  172.0  86  200  110  140  86.0   0.0         0.0
4    0.0  -9   26   20   -9  -9.0  -9.0        -9.0

In [104]:
df.describe()

1254            0  ...          0.2   Unnamed: 7
count  2939.000000  2939.000000  ...  2645.000000  2352.000000
mean    132.321980    13.954406  ...     5.419282    -1.500638
std     377.950388    35.218475  ...    28.701144     6.095486
min      -9.000000    -9.000000  ...    -9.000000    -9.000000
25%      -9.000000    -9.000000  ...    -9.000000    -9.000000
50%       0.000000     0.000000  ...    -9.000000     0.000000
75%      17.000000     3.000000  ...     1.000000     2.000000
max    5002.000000   134.000000  ...    87.000000    12.000000

[8 rows x 7 columns]

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2939 entries, 0 to 2938
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   1254        2939 non-null   float64
 1   0           2939 non-null   int64  
 2   40          2939 non-null   int64  
 3   1           2939 non-null   int64  
 4   1.1         2939 non-null   object 
 5   0.1         2645 non-null   float64
 6   0.2         2645 non-null   float64
 7   Unnamed: 7  2352 non-null   float64
dtypes: float64(4), int64(3), object(1)
memory usage: 183.8+ KB


In [106]:
df = df.rename(columns={'1254': 'col1','0':'col2','40':'col3','1':'col4','1.1':'col5','0.1':'col6','0.2':'col7','Unnamed: 7':'col8'})

In [107]:
df.head()

col1  col2  col3  col4 col5  col6  col7  col8
0   -9.0     2   140     0  289  -9.0  -9.0  -9.0
1    0.0    -9    -9     0   12  16.0  84.0   0.0
2    0.0     0     0     0  150  18.0  -9.0   7.0
3  172.0    86   200   110  140  86.0   0.0   0.0
4    0.0    -9    26    20   -9  -9.0  -9.0  -9.0

In [108]:
df=df.drop(columns=['col5'])

In [109]:
## Data preprocessing
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2939 entries, 0 to 2938
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   col1    2939 non-null   float64
 1   col2    2939 non-null   int64  
 2   col3    2939 non-null   int64  
 3   col4    2939 non-null   int64  
 4   col6    2645 non-null   float64
 5   col7    2645 non-null   float64
 6   col8    2352 non-null   float64
dtypes: float64(4), int64(3)
memory usage: 160.9 KB


In [110]:
#replacing all null values with mean of respective columns
x=df['col6'].mean()
df['col6'].fillna(value = x, inplace = True)
x=df['col7'].mean()
df['col7'].fillna(value = x, inplace = True)
x=df['col8'].mean()
df['col8'].fillna(value = x, inplace = True)

In [111]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2939 entries, 0 to 2938
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   col1    2939 non-null   float64
 1   col2    2939 non-null   int64  
 2   col3    2939 non-null   int64  
 3   col4    2939 non-null   int64  
 4   col6    2939 non-null   float64
 5   col7    2939 non-null   float64
 6   col8    2939 non-null   float64
dtypes: float64(4), int64(3)
memory usage: 160.9 KB


In [112]:
df.head()

col1  col2  col3  col4  col6  col7  col8
0   -9.0     2   140     0  -9.0  -9.0  -9.0
1    0.0    -9    -9     0  16.0  84.0   0.0
2    0.0     0     0     0  18.0  -9.0   7.0
3  172.0    86   200   110  86.0   0.0   0.0
4    0.0    -9    26    20  -9.0  -9.0  -9.0

In [113]:
from sklearn.model_selection import train_test_split

In [114]:
X=df.loc[:, df.columns!="col8"]
X.head()

col1  col2  col3  col4  col6  col7
0   -9.0     2   140     0  -9.0  -9.0
1    0.0    -9    -9     0  16.0  84.0
2    0.0     0     0     0  18.0  -9.0
3  172.0    86   200   110  86.0   0.0
4    0.0    -9    26    20  -9.0  -9.0

In [115]:
y=df["col8"]
y.head()

0   -9.0
1    0.0
2    7.0
3    0.0
4   -9.0
Name: col8, dtype: float64

In [116]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2939 entries, 0 to 2938
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   col1    2939 non-null   float64
 1   col2    2939 non-null   int64  
 2   col3    2939 non-null   int64  
 3   col4    2939 non-null   int64  
 4   col6    2939 non-null   float64
 5   col7    2939 non-null   float64
 6   col8    2939 non-null   float64
dtypes: float64(4), int64(3)
memory usage: 160.9 KB


In [117]:
print(df.shape)
print(X.shape)
print(y.shape)

(2939, 7)
(2939, 6)
(2939,)


In [118]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 10)
X_train.head()

col1  col2  col3  col4       col6      col7
5       -9.0    -9    -9    -9  -9.000000 -9.000000
252      0.0     0     0     0  21.000000 -9.000000
199   1274.0     0    43     0   0.000000  0.000000
1118     1.0     1    -9    -9   8.719471  5.419282
886     12.0    86     2    -9   2.000000 -9.000000

In [119]:
X_test.head()

col1  col2  col3  col4  col6  col7
675    -9.0    -9    -9    -9  -9.0  -9.0
862     0.0     0     0     0   4.0   3.0
183   125.0    73   176    80  74.0   0.0
2061    0.0    -9    -9     0  26.0  85.0
955    -9.0    -9    -9    -9  -9.0  -9.0

Naive Bayes

In [120]:
means = X_train.groupby(y_train).apply(np.mean) 
stds = X_train.groupby(y_train).apply(np.std)
probs = X_train.groupby(y_train).apply(lambda x: len(x))/X_train.shape[0]

In [121]:
print(means)
print(stds)
print(probs)

                  col1       col2       col3       col4       col6       col7
col8                                                                         
-9.000000     1.798322  22.724832  52.994966   2.494966  -8.270134  -8.565436
-1.500638   611.269036   0.565990  23.043147  -4.086294   4.536286   2.951167
 0.000000    71.711864  36.888620  88.782082  49.559322  50.615012  41.438257
 1.000000    -7.659389  -4.951965  -8.441048  -7.462882   0.432314   0.445415
 2.000000    10.359375  54.546875   0.234375  -5.859375  -3.820312  -7.031250
 3.000000    -5.463415  -5.682927  -5.463415  -5.073171  -3.987805  -6.487805
 4.000000    -3.926829  -4.121951  -3.926829  -3.146341  -0.060976  -4.243902
 5.000000    -3.410959  -3.260274  -3.410959  -2.904110   3.130137  -5.547945
 5.400000     1.000000   1.000000   1.000000   0.000000  11.000000  10.000000
 6.000000    -2.444444  -2.592593  -2.611111  -2.388889   5.601852  -5.620370
 7.000000    -2.984127  -2.984127  -2.984127  -2.301587   6.2222

Function to perform naive baiyes classification

In [122]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [123]:
y_pred = model.predict(X_test)

In [124]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

14.845411024451467

In [125]:
# Predicting the Test set results
from sklearn.metrics import mean_squared_error
y_pred = model.predict(X_test)
print('Coefficients: \n', model.coef_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % model.score(X_test, y_test))

Coefficients: 
 [ 0.00080917 -0.06158086 -0.04501709 -0.11864999  0.28804053 -0.06046657]
Mean squared error: 14.85
Variance score: 0.50


In [126]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
from sklearn.metrics import mean_squared_log_error,explained_variance_score
from sklearn import metrics

In [127]:
prediction = model.predict(X_test)
print('\n\nMetrics for model evualtion:\n\n')

mean_sq_error = mean_squared_error(y_test,prediction)
mean_abs_error = mean_absolute_error(y_test,prediction)
R2_score = metrics.r2_score(y_test,prediction)
explained_variance_score = metrics.explained_variance_score( y_test,prediction, multioutput='uniform_average')

print(f' Mean-sq-error            : {mean_sq_error}\n\n Mean-abs-error           : {mean_abs_error}\n\n R2-score                 : {R2_score}\n\n Explained-variance-score : {explained_variance_score}\n')




Metrics for model evualtion:


 Mean-sq-error            : 14.845411024451467

 Mean-abs-error           : 2.932858061697213

 R2-score                 : 0.5042264898652904

 Explained-variance-score : 0.5042800231737037



In [128]:
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB
from sklearn import linear_model
clf = linear_model.BayesianRidge()

In [129]:
clf.fit(X_train,y_train)

BayesianRidge(alpha_1=1e-06, alpha_2=1e-06, alpha_init=None,
              compute_score=False, copy_X=True, fit_intercept=True,
              lambda_1=1e-06, lambda_2=1e-06, lambda_init=None, n_iter=300,
              normalize=False, tol=0.001, verbose=False)

In [130]:
clf.predict(X_test)

array([-4.91837783e-01,  5.03431612e-01, -9.68429143e-01,  2.83431730e+00,
       -4.91837783e-01, -8.16444851e+00, -4.38058429e+00, -1.17461760e+00,
        4.81811336e-01, -1.63795876e+00,  3.42544508e+00,  1.79779014e+00,
        3.11018373e+00,  4.81811336e-01, -6.84498260e+00,  3.16933669e+00,
       -1.38193335e+00, -6.65143767e+00,  1.77135964e+00,  3.11018373e+00,
        3.11018373e+00, -4.86758930e+00, -4.91837783e-01, -2.03584198e+00,
       -8.26701219e+00, -3.79997882e+00,  4.81811336e-01, -8.29312815e-01,
       -6.64819606e+00, -5.51692933e+00, -3.60390807e+00, -4.91837783e-01,
       -6.64819606e+00, -8.88208580e+00,  5.80798558e+00,  2.08423267e+00,
        3.11018373e+00,  6.85583527e-01,  1.77135964e+00, -4.91837783e-01,
       -4.21824928e+00,  5.23510052e+00,  1.77135964e+00,  1.43877198e+00,
        4.08933039e+00, -1.04138942e+01,  5.99043001e-01,  2.94356027e+00,
       -4.91837783e-01, -6.58671954e+00,  1.96211733e-01,  3.98008743e+00,
       -4.91837783e-01,  

In [131]:
from sklearn.metrics import mean_squared_error
y_pred = clf.predict(X_test)
print('Coefficients: \n', clf.coef_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % model.score(X_test, y_test))

Coefficients: 
 [ 0.0008104  -0.06147651 -0.04510334 -0.11723166  0.28644253 -0.06012279]
Mean squared error: 14.84
Variance score: 0.50


In [132]:
prediction = clf.predict(X_test)
print('\n\nMetrics for model evualtion:\n\n')

mean_sq_error = mean_squared_error(y_test,prediction)
mean_abs_error = mean_absolute_error(y_test,prediction)
R2_score = metrics.r2_score(y_test,prediction)
explained_variance_score = metrics.explained_variance_score( y_test,prediction, multioutput='uniform_average')

print(f' Mean-sq-error            : {mean_sq_error}\n\n Mean-abs-error           : {mean_abs_error}\n\n R2-score                 : {R2_score}\n\n Explained-variance-score : {explained_variance_score}\n')



Metrics for model evualtion:


 Mean-sq-error            : 14.841750786927637

 Mean-abs-error           : 2.932494612339554

 R2-score                 : 0.5043487262117363

 Explained-variance-score : 0.504404973879818

